name: Tests

on: [push, pull_request]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - uses: actions/setup-node@v3
    - name: System Setup
      shell: bash
      run: |
        sudo apt update -y
        sudo apt install -y -qq curl libcurl4-openssl-dev clang-tools clang-tidy
    - name: Run Tests
      run: |
        ## deps
        npm install
        pip install cpplint

        ## checks
        make tidy lint check

        ## tests
        make tests NO_VALGRIND=1 NO_BRIEF=1 VALIDATE_WITH_TAP_PARSER=1

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
    - uses: actions/setup-python@v1
    - name: System Setup
      shell: bash
      run: |
        brew install openssl curl clang-format
    - name: Run Tests
      run: |
        ## deps
        npm install
        pip install cpplint

        ## checks
        make lint check

        ## tests
        make tests NO_VALGRIND=1 NO_BRIEF=1 VALIDATE_WITH_TAP_PARSER=1
