name: Tests

on: [push, pull_request]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: System Setup
      shell: bash
      run: |
        sudo apt install -qq libcurl4-opensll-dev
    - name: Run Tests
      run: |
        npm install
        make clean tests NO_VALGRIND=1 NO_BRIEF=1 VALIDATE_WITH_TAP_PARSER=1

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
    - name: System Setup
      shell: bash
      run: |
        : # noop
    - name: Run Tests
      run: |
        npm install
        make clean tests NO_VALGRIND=1 NO_BRIEF=1 VALIDATE_WITH_TAP_PARSER=1
