name: Tests

on: [push, pull_request]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: System Setup
      shell: bash
      run: |
        sudo apt install -qq libcurl4-gnutls-dev
    - name: Run Tests
      run: |
        make clean test NO_VALGRIND=1 NO_BRIEF=1

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: System Setup
      shell: bash
      run: |
        : # noop
    - name: Run Tests
      run: |
        make clean test NO_VALGRIND=1 NO_BRIEF=1
