name: Tests

on: [push, pull_request]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - uses: actions/setup-node@v3
    - name: System Setup
      shell: bash
      run: |
        sudo apt update -y
        sudo apt install -y -qq curl libcurl4-openssl-dev clang-tools
    - name: Run Tests
      run: |
        ## deps
        npm install
        pip install cpplint

        ## tests
        make check
        make tests NO_VALGRIND=1 NO_BRIEF=1 VALIDATE_WITH_TAP_PARSER=1

        ## lint
        curl -Lo- get.bpkg.sh | bash
        bpkg run lint

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
    - uses: actions/setup-python@v1
    - name: System Setup
      shell: bash
      run: |
        brew install openssl curl
    - name: Run Tests
      run: |
        ## deps
        npm install
        pip install cpplint

        ## tests
        make tests NO_VALGRIND=1 NO_BRIEF=1 VALIDATE_WITH_TAP_PARSER=1
        make check

        ## lint
        export PRFEFIX=/usr/local
        curl -Lo- get.bpkg.sh | bash
        bpkg run lint
